### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by dscription** [kinectron/kinectron-examples#10]
I am having the same issue on both firefox and chrome. I cant seem to find a solution.

When I load my p5.js sketch i get an error saying:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ... (Reason: CORS request did not succeed).

Is there a permissions or security setting I need to change in my browser?

**Comment by montoyamoraga** [comment]
hi @playdscription,
can you let us know what kind of setup are you using?
how are you setting up the client side?
what kind of server are you using?

**Comment by lisajamhoury** [comment]
Also are you using the p5 editor in the browser or are you serving your p5 sketch via a local server (like simplehttpserver)? Unfortunately because of new security requirements for https in both Chrome and Firefox Kinectron cannot currently serve to the p5 editor website. See [#45](https://github.com/kinectron/kinectron/issues/45). 

I think I found a workaround for this but haven't yet implemented.

**Comment by dscription** [comment]
@montoyamoraga I am using a PC and developing locally on my PC. I have not set up and servers. I launch Kinectron server and then load my index.html file to the browser (I am not using the p5 editor).

**Comment by lisajamhoury** [comment]
Try running your p5 code with a local server. Here's [an explanation on how to do it](https://github.com/processing/p5.js/wiki/Local-server) and here's [an explainer video from Dan Shiffman](https://www.youtube.com/watch?v=UCHzlUiDD10). Does that help?

@montoyamoraga May have some other suggestions/references as well.

**Comment by dscription** [comment]
@lisajamhoury I ran my code with a local server and that solved the problem. Thank you very much for your help.

**Comment by lisajamhoury** [comment]
Great! Glad it worked!
