### ISSUE TITLE
Make them run with recorded data

### ISSUE THREAD

**Issue by montoyamoraga** [kinectron/kinectron-examples#3]

**Comment by lisajamhoury** [comment]
Started work on P5 examples. Here's where we're at: 

Skeleton -- working 
Joint -- working
Beach -- working, but rough
Catch -- working, but needs new recorded skeleton
Getting started -- nothing yet
Getting started multiple -- nothing yet
Multiframe -- nothing yet

Next steps will be to clean up beach example and record new data for catch. 

Then I need to streamline the recording to playback process and document how to do this. Could use some help with documentation and thinking about best way to do this.

**Comment by lisajamhoury** [comment]
Also, we then need to put the recorded examples running on website. Not sure best way to do this yet -- with p5 Alpha Editor? Or not?

**Comment by lisajamhoury** [comment]
Here's the plan for getting this done:
[] streamline the way that key is recorded
[] streamline how all video is recorded
[] streamline the way that skeleton data is recorded
[] put video to images function in client side library

**Comment by lisajamhoury** [comment]
Everything on my previous to-do is done now. 

I didn't put the videoToImages function into the client-side library. I decided for now not to include this functionality there for now because I see it as a low priority, but maybe it would make sense down the line. 

@montoyamoraga The examples repo is now ready for you to refactor to make more readable, etc. Looking forward to your feedback. 

I've started to put the examples that run with recorded data into the alpha editor so that I can embed them on the documentation site. I should be able to finish work on that this week.

**Comment by lisajamhoury** [comment]
I added the two player joint example and the key/beach example that run with recorded data to the website. [Commit](https://github.com/kinectron/kinectron.github.io/commit/5c7500774e435592932b694506067259777c3ce0). They are live at https://kinectron.github.io/docs/example-simple-skeleton.html

I created the beach example natively with a p5 canvas on the page, rather than using an iframe with the p5 alpha editor, because the alpha editor was giving a CORS error. Loading natively fixed the issue for that particular example. 

I'm now trying to run the skeleton and joint examples natively, but I'm running into a MIME error with p5/loadJSON, which I use to load the recorded skeleton data. So these two examples are still running from p5 alpha editor embeds.

**Comment by lisajamhoury** [comment]
Fixed MIME error and these examples are now running natively without the p5 alpha editor iframe on the page. 

@montoyamoraga assigning this to you now to review when you have time. I've gone as far as I can go on the p5 examples for now.

**Comment by lisajamhoury** [comment]
I got all the examples I could running with recorded data, so closing this thread.
