### ISSUE TITLE
Help with sketch

### ISSUE THREAD

**Issue by rayuli** [kinectron/kinectron-examples#8]
Hi, I have this sketch where I draw an image at rightHandX, rightHandY. 
It works perfect with one "body", but when more bodies comes in, the first body image starts to "glicth" and change color.
<img width="1195" alt="Captura de pantalla 2019-09-29 a las 13 51 08" src="https://user-images.githubusercontent.com/24292157/65832122-72416f80-e2c0-11e9-931c-b9ea51f5cb2f.png">
<img width="1112" alt="Captura de pantalla 2019-09-29 a las 13 52 07" src="https://user-images.githubusercontent.com/24292157/65832125-72da0600-e2c0-11e9-85de-d2fe371cbaed.png">

Any ideas? thanks in advance

`
function trackBody(body) {
   background(0,0,255,100);

 //Mano derecha
    var val;
    val = body.joints[kinectron.HANDRIGHT].depthX;
    var rightHandX =  map(val,0,1,0,width);
    val = body.joints[kinectron.HANDRIGHT].depthY;
    var rightHandY = map(val,0,1,0,height); //height numbers bigger at the bottom

if (body.bodyIndex == 0){
image(bicho[0], rightHandX, rightHandY,100,100);
  }else if (body.bodyIndex == 1){

image(bicho[1], rightHandX, rightHandY,100,100);
  }else if (body.bodyIndex == 2){
image(bicho[2], rightHandX, rightHandY,100,100);
  }else if (body.bodyIndex == 3){
image(bicho[0], rightHandX, rightHandY,100,100);
  }else if (body.bodyIndex == 4){
image(bicho[1], rightHandX, rightHandY,100,100);
  }else if (body.bodyIndex == 5){
image(bicho[2], rightHandX, rightHandY,100,100);
  }

}

`

**Comment by lisajamhoury** [comment]
Take a look at this example that uses the unique tracking IDs of the bodies. 

https://kinectron.github.io/docs/example-two-player-joints.html

**Comment by rayuli** [comment]
Hi!
oook, got it :)
<3

**Comment by lisajamhoury** [comment]
glad it helped!

**Comment by rayuli** [comment]
Hi! 
so, I have this example working where I draw an image at rightHandX, rightHandY. It works with several "bodies", the problem that I have now is when that body disappears from the screen, the image doesn't get deleted. I have tried this but it doesn't work: 

 if (hand.depthX > 0.9 || hand.depthX < 0.29 ||
          hand.cameraZ > 0.6|| hand.cameraZ < 4) {

  hands[hand.trackingId] = hand;
} else{

  delete hands[hand.trackingId];
}

thanks again! <3

Juli

<img width="1001" alt="Captura de pantalla 2019-10-17 a las 12 39 15" src="https://user-images.githubusercontent.com/24292157/67001968-27569300-f0db-11e9-8248-0991e26077fd.png">

**Comment by montoyamoraga** [comment]
@rayuli are you working with p5.js?
can you share with us the full working example on the p5.js web editor?
https://editor.p5js.org/
i would like to examine the logic and if you share it on the web editor, it's easier for me to comment on it, best!

**Comment by rayuli** [comment]
Hi! thanks for answering :) I appreciate a lot your help.

yes I'm working with p5.js.
Here it is my example on the web editor: 

https://editor.p5js.org/julimarinocampo@gmail.com/sketches/WdcU4Uc27

**Comment by montoyamoraga** [comment]
@rayuli sure, happy to help.
your code was long so i couldn't read it all, i am a spanish-speaker though,
so i could read the comments :)

so you declared hands as an empty object with
"let hands = {}"
and then you added to it the corresponding "hand" according to the id with:
hands[hand.trackingId] = hand;
and then you are trying to delete it with the keyword "delete"

i looked up the keyword "delete" here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete
and i'm not sure that it is doing what you are trying to do, which is stop drawing the corresponding image when the body disappears from the screen, right?

i would do another approach, which is iterate over the skeletons that Kinect detects, and draw the octopi according to them for every frame, instead of pulling that data and adding it to this object hands, does that make sense?

**Comment by rayuli** [comment]
Hi! I've done another example, and I get the same "result", that is

 when the "body" leaves the scene the image persists. (sorry for my english haha).

/*EMOJIS
Rayuli Ocampo Octubre 2019*/


var kinectron = null;
var bodies = {};


var emojis =  ['👶', '👶🏻', '👶🏼', '👶🏽', '👶🏾', '👶🏿', '👦', '👦🏻', '👦🏼', '👦🏽', '👦🏾', '👦🏿', '👧', '👧🏻', '👧🏼', '👧🏽', '👧🏾', '👧🏿', '👨', '👨🏻', '👨🏼', '👨🏽', '👨🏾', '👨🏿', '👩', '👩🏻', '👩🏼', '👩🏽', '👩🏾', '👩🏿',  '👴', '👴🏻', '👴🏼', '👴🏽', '👴🏾', '👴🏿', '👵', '👵🏻', '👵🏼', '👵🏽', '👵🏾', '👵🏿'];
var emoji;


function preload() {


}



function setup() {
  
    createCanvas(windowWidth, windowHeight);
    background(0);
    noStroke();

    initKinectron();

  emoji = random(emojis);
}


function draw() {
    
}


function initKinectron() {

    var address = {
        host: '192.168.1.2',
        port: 9001,
        path: '/'
    };

    kinectron = new Kinectron('kinectron', address);
  
    kinectron.makeConnection();

    // Define and create an instance of kinectron


    kinectron.startTrackedBodies(bodyTracked);
}


function bodyTracked(body) {

   background(0);

   bodies[body.trackingId] = {
    joints: body.joints,
  }

  for(var body in bodies) {
    // Draw all the joints
    var joints = bodies[body].joints;
  
    // Get all the joints off the tracked body and do something with them

    var head = getPos(joints[kinectron.HEAD]);
    
    noFill()
    stroke(255);
    strokeWeight(10);

  // cabeza

  textSize(50);
  text(emoji, head.x, head.y);
    
  }
  
}

function getPos(joint) {
  return createVector((joint.depthX * width/2), (joint.depthY * width/2));
}

<img width="597" alt="Captura de pantalla 2019-10-18 a las 17 47 30" src="https://user-images.githubusercontent.com/24292157/67108726-66661080-f1cf-11e9-8d83-486000c09a7a.png">

**Comment by montoyamoraga** [comment]
hi @rayuli the formatting on the code above is weird and it was hard to read.
i don't have a kinectron near me for testing, but did you try this example?
https://kinectron.github.io/docs/example-two-player-joints.html
that one should work, and if it does, please study every line very carefully,
making sure you understand what every line is doing.
this is great feedback for us, and we need to write more documentation, 
so that it is clearer and we have more examples.
i will get my kinect back soon and i hope i can write some more examples
next month. sorry we cannot help more right now!
