### ISSUE TITLE
skeleton example

### ISSUE THREAD

**Issue by rayuli** [kinectron/kinectron-examples#9]
Hi!
I'd like to know how to draw lines betwen the different joints to form a basic skeleton sketch for more than one body. 
I´ve done it with the startTrackedBodies function but it only works with one body. 
thanks in advance. 

J.

<img width="133" alt="Captura de pantalla 2019-10-02 a las 19 30 00" src="https://user-images.githubusercontent.com/24292157/66067238-79c87900-e54b-11e9-981d-310ed5b66b3a.png">

**Comment by lisajamhoury** [comment]
In order to separate and identify the bodies, you will need to start by doing something like [this example with the hand joints](https://kinectron.github.io/docs/example-two-player-joints.html), but you will need to extend it to the full bodies rather than using the tracked joint function.

See [this example](https://gist.github.com/ShawnMa16/4cd254048f1bc8ec0d14abc5a8f657dd) from @ShawnMa16. Lines 5-17 show you how to get the trackingID for each body from startTrackedBodies. 

So you need to combine those two examples, then you can add your code to draw the skeleton in place of the code that draws the hands and labels at the end of the hand example. 

This is a great idea for a new example. When you get it running, please consider sharing your code so I can include in the examples for others.

**Comment by rayuli** [comment]
Hi!
Thanks a lot for answering!
I am currently working on an audiovisual performance for kids using several kinectron sketches, when I get this running, I will share the code.
thanks again!

**Comment by lisajamhoury** [comment]
Great, sounds interesting! I am closing the issue for now, but feel free to reopen the issue if you have additional questions as you work on this.
